---
# First run:
# sudo dnf install ansible

- hosts: localhost

  connection: local
  gather_facts: yes
  become: yes

  vars:
    ansible_user: jaso
    ansible_sudo_pass: "{{ ansible_ssh_pass }}"
    msg: |

          Good gnome extentions:
          ----------------------
          - Clipboard Indicator
          - Dash to Dock
          - No Topleft Hot Corner
          - Refresh wifi connections
          - Sound Input & Output Device Chooser
          - Top Panel Workspace Scroll
          - Hide Activities Button

  vars_prompt:
    - name: ansible_ssh_pass
      prompt: "Your password"
      private: yes

  tasks:

    - name: Enable passwordless sudo
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Enable RPM Fusion
      dnf:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
        - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-31.noarch.rpm
        #- https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-31.noarch.rpm

    - name: Check for nVidia gpu
      shell: lspci | grep -qi nvidia
      ignore_errors: yes
      changed_when: False
      register: nvidiaPresent

    - name: Install nVidia drivers
      dnf:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
        - xorg-x11-drv-nvidia
        - akmod-nvidia
      when: nvidiaPresent.rc == 0

    - name: Add VSCode repository
      yum_repository:
        name: VSCode
        baseurl: https://packages.microsoft.com/yumrepos/vscode
        gpgkey: https://packages.microsoft.com/keys/microsoft.asc
        description: VSCode

    - name: Install rpm packages
      dnf:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
        - code
        #- chromium
        #- chromium-libs-media-freeworld
        #- dconf-editor
        - ffmpeg # for h264 (netflix, youtube), from rpmfusion-free
        #- gnome-mpv
        - gnome-tweaks
        - htop
        - nmap
        - pavucontrol
        - pwgen
        - ranger
        - remmina
        - transmission
        - unar
        - vim
        - virt-manager
        - xclip
        #- libgnome-keyring # Needed for Nextcloud from fedora repo

    - name: Append jaso to libvirt group
      user:
        name: jaso
        append: yes
        groups: libvirt

    - name: 
      flatpak_remote:
        name: flathub
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

    - name: Install flatpak packages
      flatpak:
        name: "{{ item }}"
      with_items:
        - com.spotify.Client
        - im.riot.Riot
        - org.nextcloud.Nextcloud

    - name: Enable services
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - sshd
        - libvirtd

    - name: Add VSCode extensions
      shell: code --install-extension "{{ item }}"
      become: false
      with_items:
        - eamodio.toggle-excluded-files
        # - Gruntfuggly.todo-tree
        # - ionutvmi.path-autocomplete
        # - ms-azuretools.vscode-docker
        # - ms-kubernetes-tools.vscode-kubernetes-tools
        - ms-python.python
        - ms-vscode-remote.remote-containers
        # - ms-vscode-remote.remote-ssh
        # - ms-vscode-remote.remote-ssh-edit
        # - ms-vscode-remote.remote-ssh-explorer
        # - redhat.vscode-yaml
        # - vscode-icons-team.vscode-icons
        - vscoss.vscode-ansible
      tags: test

    - name: Set gsettings
      shell: ./gsettings.sh
      become: false

    - debug:
        msg: "{{ msg }}"
