---
# First run:
# sudo dnf install ansible

- hosts: localhost

  connection: local
  gather_facts: yes
  become: yes

  vars:
    ansible_user: jaso
    ansible_sudo_pass: "{{ ansible_ssh_pass }}"
    msg: |

          Good gnome extentions:
          ----------------------
          - Clipboard Indicator
          - Dash to Dock
          - No Topleft Hot Corner
          - Sound Input & Output Device Chooser
          - KStatusNotifierItem/AppIndicator Support

  vars_prompt:
    - name: ansible_ssh_pass
      prompt: "Your password"
      private: yes

  tasks:

    - name: Enable passwordless sudo
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Enable RPM Fusion
      dnf:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
        - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-32.noarch.rpm
        - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-32.noarch.rpm

    - name: Check for nVidia gpu
      shell: lspci | grep -qi nvidia
      ignore_errors: yes
      changed_when: False
      register: nvidiaPresent

    - name: Install nVidia drivers
      dnf:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
        - xorg-x11-drv-nvidia
        - akmod-nvidia
      when: nvidiaPresent.rc == 0

    - name: Add VSCode repository
      yum_repository:
        name: VSCode
        baseurl: https://packages.microsoft.com/yumrepos/vscode
        gpgkey: https://packages.microsoft.com/keys/microsoft.asc
        description: VSCode

    - name: Install rpm packages
      dnf:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
        #- ddrescue
        #- ffmpeg # for h264 (netflix, youtube), from rpmfusion-free
        #- gnome-tweaks
        #- libgnome-keyring # Needed for Nextcloud from fedora repo
        #- pavucontrol
        #- virt-manager
        - code
        - docker
        - docker-compose
        - flameshot
        - fontawesome-fonts
        - gnome-extensions-app
        - htop
        - nextcloud-client
        - nmap
        - pwgen
        - ranger
        - remmina
        - transmission
        - unar
        - vim

    #- name: Append jaso to libvirt group
    #  user:
    #    name: jaso
    #    append: yes
    #    groups: libvirt

    - name: 
      flatpak_remote:
        name: flathub
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

    - name: Install flatpak packages
      flatpak:
        name: "{{ item }}"
      with_items:
        - com.spotify.Client
        - com.mattermost.Desktop

    - name: Enable services
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        #- sshd
        #- libvirtd
        - dnf-makecache

    #- name: Add VSCode extensions
    #  shell: code --install-extension "{{ item }}"
    #  become: false
    #  with_items:
    #    - Gruntfuggly.todo-tree
    #    - ms-python.python
    #    - vscoss.vscode-ansible
    #    #- eamodio.toggle-excluded-files
    #    # - ms-azuretools.vscode-docker
    #    # - ms-kubernetes-tools.vscode-kubernetes-tools
    #    # - redhat.vscode-yaml
    #    # - vscode-icons-team.vscode-icons
    #  #tags: test

    - name: Find firefox profile path
      find:
        paths: /home/{{ ansible_user }}/.mozilla/firefox/
        recurse: yes
        patterns: 'prefs.js'
      become: false
      register: find_result
      tags: ff

    - debug:
        msg: "Could not find active firefox profile. Run firefox and rerun this playbook."
      when: find_result.matched == 0
      tags: ff

    - name: Deploy firefox profile settings
      copy:
        src: user.js
        dest: "{{ item.path | dirname }}/user.js"
      with_items: "{{ find_result.files }}"
      when: find_result.matched > 0
      become: false
      tags: ff

    - name: gsettings permission
      file:
        path: ./gsettings.sh
        mode: 0755

    - name: Set gsettings
      shell: ./gsettings.sh
      become: false

    - debug:
        msg: "{{ msg }}"
